[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type,Authorization,Accept"

[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[edge_functions]]
  function = "searchidtostudent"
  path = "/searchidtostudent/*"
