[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type,Authorization,Accept"

[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "searchidtostudent"
  path = "/searchidtostudent/*"

[[edge_functions]]
  function = "course-info-edge"
  path = "/course-info"

[[edge_functions]]
  function = "classbxopchfetch-edge"
  path = "/classbxopchfetch"