[[build]]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/searchidtostudent"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept"